"""Add is_deleted to Event

Revision ID: 052fca65b4ba
Revises: 
Create Date: 2025-04-12 00:14:20.460795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052fca65b4ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_open_to_all', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_roll_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_roll_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_open_to_all')
        batch_op.drop_column('start_roll_number')
        batch_op.drop_column('end_roll_number')

    # ### end Alembic commands ###
