"""add event roll number restriction columns

Revision ID: 8c5231a5f723
Revises: a6fc50b46d38
Create Date: 2025-07-08 22:52:01.292318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5231a5f723'
down_revision = 'a6fc50b46d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open_to_all', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_roll_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_roll_number', sa.String(length=20), nullable=True))

    op.create_table('event_course',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
        sa.PrimaryKeyConstraint('event_id', 'course_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('end_roll_number')
        batch_op.drop_column('start_roll_number')
        batch_op.drop_column('is_open_to_all')

    op.drop_table('event_course')

    # ### end Alembic commands ###
