"""add cascade delete to student feedback responses

Revision ID: a6fc50b46d38
Revises: 6979a92de978
Create Date: 2025-07-03 18:58:43.267112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fc50b46d38'
down_revision = '6979a92de978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_response', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_feedback_response_student_id_student', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_response', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_response_student_id_student', type_='foreignkey')
        batch_op.create_foreign_key('fk_feedback_response_student_id_student', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
